# Generated by Django 4.1.7 on 2023-03-23 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=5000)),
                ('deadline', models.DateField(verbose_name='Дедлайн')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('completed_at', models.DateField()),
                ('restrictions', models.ManyToManyField(to='user_teams.positions')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tasks', models.ManyToManyField(to='user_teams.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_teams.positions', verbose_name='Должность')),
                ('selected_task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='user_teams.tasks', verbose_name='Задача')),
                ('team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='user_teams.team', verbose_name='Команда')),
            ],
        ),
    ]
