# Generated by Django 4.1.7 on 2023-03-23 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='selected_task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='user_teams.tasks', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='users',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='user_teams.team', verbose_name='Команда'),
        ),
    ]
