# Generated by Django 4.1.7 on 2023-04-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_teams', '0002_alter_tasks_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_selected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
