# Generated by Django 4.1.7 on 2023-04-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_teams', '0005_alter_team_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='in_team', through='user_teams.TaskToTeam', to='user_teams.tasks', verbose_name='Задачи'),
        ),
    ]
